# Generated by Django 4.2.7 on 2024-05-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresetcode_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
